version: '3.3'

networks:
  aw-ec-network:
    driver: bridge

volumes:
  aw-ec-mysql-volume:

services:
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "algamensagens"
    ports:
      - "3306:3306"
    networks:
      - aw-ec-network
    volumes:
      - aw-ec-mysql-volume:/var/lib/mysql
  pais-api:
    image: vimagick/json-server
    command: -H 0.0.0.0 -p 3000 -w db.json
    ports:
      - "3000:3000"
    volumes:
      - ./config/db.json:/data/db.json
      