version: '3.3'

networks:
  aw-ec-network:
    driver: bridge

volumes:
  aw-ec-mysql-volume:

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "16379:6379"
    networks:
      - aw-ec-network
  
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "awecommerce"
    ports:
      - "13306:3306"
    networks:
      - aw-ec-network
    volumes:
      - aw-ec-mysql-volume:/var/lib/mysql