resilience4j:
  circuitbreaker:
    instances:
      avaliacaoCB:
        failureRateThreshold: 50 #Padrao
        slidingWindowSize: 8
        minimumNumberOfCalls: 4
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 60s
        #maxWaitDurationInHalfOpenState