resilience4j:
  circuitbreaker:
    instances:
      avaliacaoCB:
        failureRateThreshold: 50 #Padrao
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 5
        #waitDurationInOpenState: 30s
        #maxWaitDurationInHalfOpenState