resilience4j:
  circuitbreaker:
    instances:
      editors:
        slidingWindowSize: 8
        minimumNumberOfCalls: 4
        permittedNumberOfCallsInHalfOpenState: 4
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        maxWaitDurationInHalfOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10