spring:
  datasource.mensagens:
    username: root
    url: jdbc:mysql://localhost:3306/awmensagens?createDatabaseIfNotExist=true&serverTimezone=UTC
    password:
  datasource.usuarios:
    username: root
    url: jdbc:mysql://localhost:3306/awusuarios?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: