spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/awmensagens?createDatabaseIfNotExist=true&serverTimezone=UTC
    password:
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml
  main:
    allow-bean-definition-overriding: true
bucket4j:
  enabled: true
  filter-method: servlet #muito importante, web/flux
  filters:
    - cache-name: mensagemRateLimit
      url: .*
      rate-limits:
        - bandwidths:
            - capacity: 5
              time: 1
              unit: minutes