spring:
  main:
    allow-bean-definition-overriding: 'true'
  cache:
    type: jcache
    jcache:
      provider: com.hazelcast.cache.impl.HazelcastServerCachingProvider
      config: classpath:hazelcast.xml
server:
  port: '8080'
bucket4j:
  enabled: true
  filters:
    - cache-name: avaliacaoRateLimit #nome do limit
      url: /avaliacoes* # escaneia todas URLS .* ou /avaliacoes*
      filter-order: 100 # Devido ao spring security filter precisar se aplicado antes
      rate-limits:
        - skip-condition: "getRequestURI().equals('/')" #ignora url raiz
          expression: "@segurancaService.getUsuario()" #pega nome do usuario
          bandwidths:
            - capacity: 5
              time: 1
              unit: minutes
              